<?php if ( ! defined( 'ABSPATH' ) ) {
	die( 'Forbidden' );
}

/**
 * Starter Page Templates.
 *
 * Registers the bundled whole-page starter layouts (Landing / About / Pricing /
 * Contact) with the page-builder's native predefined-templates system, so they
 * show up as read-only starters under the builder's Templates → Full Templates
 * tab. Selecting one drops the entire layout onto the page canvas.
 *
 * The layouts are plain page-builder atom trees stored as JSON under
 * `up-templates/starter-pages/<slug>.json` (generated by the sibling
 * `_src/build.mjs` from verified attribute templates, so the saved shapes are
 * always schema-correct). This hooks the plugin filter:
 *
 *     fw_ext_builder:predefined_templates:page-builder:full
 *
 * — each returned entry is `array( 'title' => …, 'json' => '<tree-json>' )`.
 * Predefined entries render without a Delete button (read-only), which is the
 * Starter-Templates semantics we want.
 *
 * A theme can extend or replace the set with the
 * `unysonplus_starter_page_templates` filter (keyed slug => { title, file|json }).
 */

if ( ! function_exists( 'unysonplus_starter_page_templates_dir' ) ) :
/**
 * Absolute path to the bundled starter-templates folder (child-theme aware).
 */
function unysonplus_starter_page_templates_dir() {
	$rel = '/up-templates/starter-pages';
	if ( function_exists( 'is_child_theme' ) && is_child_theme() ) {
		$child = get_stylesheet_directory() . $rel;
		if ( is_dir( $child ) ) {
			return $child;
		}
	}
	return get_template_directory() . $rel;
}
endif;

if ( ! function_exists( 'unysonplus_starter_page_templates' ) ) :
/**
 * The registered starter templates, each as slug => array( title, file ).
 * Read from the bundled manifest.json; filterable so child themes / extensions
 * can add their own (supply a 'file' absolute path or an inline 'json' string).
 *
 * @return array
 */
function unysonplus_starter_page_templates() {
	static $cache = null;
	if ( $cache !== null ) {
		return $cache;
	}

	$dir      = unysonplus_starter_page_templates_dir();
	$manifest = $dir . '/manifest.json';
	$list     = array();

	if ( is_readable( $manifest ) ) {
		$decoded = json_decode( (string) file_get_contents( $manifest ), true );
		if ( is_array( $decoded ) ) {
			foreach ( $decoded as $entry ) {
				if ( empty( $entry['slug'] ) ) {
					continue;
				}
				$slug = sanitize_key( $entry['slug'] );
				$list[ $slug ] = array(
					'title' => isset( $entry['title'] ) ? (string) $entry['title'] : ucfirst( $slug ),
					'file'  => $dir . '/' . $slug . '.json',
				);
			}
		}
	}

	/**
	 * Filter the starter page templates.
	 *
	 * @param array $list slug => array( 'title' => string, 'file' => path[, 'json' => string ] )
	 */
	$cache = apply_filters( 'unysonplus_starter_page_templates', $list );
	return $cache;
}
endif;

if ( ! function_exists( 'unysonplus_register_starter_page_templates' ) ) :
/**
 * Feed the starter templates into the builder's Full Templates list.
 *
 * @param array $templates Existing predefined templates (id => {title, json}).
 * @return array
 */
function unysonplus_register_starter_page_templates( $templates ) {
	if ( ! is_array( $templates ) ) {
		$templates = array();
	}

	foreach ( unysonplus_starter_page_templates() as $slug => $tpl ) {
		// An inline 'json' string wins; otherwise read the bundled file.
		$json = '';
		if ( isset( $tpl['json'] ) && is_string( $tpl['json'] ) && $tpl['json'] !== '' ) {
			$json = $tpl['json'];
		} elseif ( ! empty( $tpl['file'] ) && is_readable( $tpl['file'] ) ) {
			$json = (string) file_get_contents( $tpl['file'] );
		}

		// Must be a non-empty JSON array of atoms; skip anything malformed so a
		// bad file can never break the builder's template list.
		$json = trim( $json );
		if ( $json === '' ) {
			continue;
		}
		$decoded = json_decode( $json, true );
		if ( ! is_array( $decoded ) || empty( $decoded ) ) {
			continue;
		}

		$templates[ 'starter_' . $slug ] = array(
			'title' => $tpl['title'],
			'json'  => $json,
		);
	}

	return $templates;
}
endif;

add_filter( 'fw_ext_builder:predefined_templates:page-builder:full', 'unysonplus_register_starter_page_templates' );
